# Generated by Django 3.0.5 on 2020-05-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Productos', '0009_copashelados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('Productos', models.ManyToManyField(blank=True, null=True, to='Productos.Producto')),
            ],
        ),
    ]
