# Generated by Django 3.0.5 on 2020-05-19 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_copascart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copascart',
            old_name='Productos',
            new_name='Productos2',
        ),
    ]
