# Generated by Django 3.0.5 on 2020-05-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20200519_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='totalC',
            field=models.IntegerField(default=0),
        ),
    ]
