# Generated by Django 3.0.5 on 2020-05-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0013_malteada'),
        ('carts', '0007_cart_producto2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copascart',
            name='Productos',
        ),
        migrations.AddField(
            model_name='cart',
            name='Producto3',
            field=models.ManyToManyField(blank=True, null=True, to='Productos.Malteada'),
        ),
        migrations.DeleteModel(
            name='carMalteadas',
        ),
        migrations.DeleteModel(
            name='Copascart',
        ),
    ]
