# Generated by Django 3.0.5 on 2020-05-21 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_auto_20200521_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='totalC',
        ),
    ]
