# Generated by Django 3.0.5 on 2020-05-22 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0011_auto_20200521_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='Productos2',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='Productos3',
        ),
    ]
