# Generated by Django 3.0.5 on 2020-05-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0013_malteada'),
        ('carts', '0012_auto_20200521_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Producto2',
            field=models.ManyToManyField(to='Productos.CopasHelados'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Producto3',
            field=models.ManyToManyField(to='Productos.Malteada'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Productos',
            field=models.ManyToManyField(to='Productos.Producto'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(to='carts.CartItem'),
        ),
    ]
