# Generated by Django 3.0.5 on 2020-05-22 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0013_malteada'),
        ('carts', '0013_auto_20200521_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='Productos2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Productos.CopasHelados'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='Productos3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Productos.Malteada'),
        ),
    ]
