# Generated by Django 3.0.5 on 2020-05-22 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0013_malteada'),
        ('carts', '0018_auto_20200522_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='Producto1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Productos.Producto'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='Productos2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Productos.CopasHelados'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='Productos3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Productos.Malteada'),
        ),
    ]
