# Generated by Django 3.0.5 on 2020-05-22 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0019_auto_20200522_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Producto2',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Producto3',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Productos',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.Cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='line_total',
            field=models.IntegerField(default=10),
        ),
    ]
