# Generated by Django 3.0.5 on 2020-05-22 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0020_auto_20200522_1415'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
