# Generated by Django 3.0.5 on 2020-05-22 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0022_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
    ]
