# Generated by Django 3.0.5 on 2020-05-22 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0024_cartitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='Productos2',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='Productos3',
        ),
    ]
