# Generated by Django 3.0.5 on 2020-05-22 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0025_auto_20200522_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='Producto1',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
