# Generated by Django 3.0.5 on 2020-05-23 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0013_malteada'),
        ('carts', '0027_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('line_total', models.IntegerField(default=10)),
                ('Producto3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.Malteada')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('line_total', models.IntegerField(default=10)),
                ('Producto2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.CopasHelados')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.Cart')),
            ],
        ),
    ]
