# Generated by Django 3.0.5 on 2020-05-18 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_producto_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('nombre', 'slug')},
        ),
    ]
