# Generated by Django 3.0.5 on 2020-05-19 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0007_copashelados'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CopasHelados',
        ),
    ]
