# Generated by Django 3.0.5 on 2020-05-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0009_copashelados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copashelados',
            name='image',
            field=models.ImageField(null=True, upload_to='CopasHelados/images'),
        ),
    ]
