# Generated by Django 3.0.5 on 2020-05-20 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0011_malteada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Malteada',
        ),
    ]
