# Generated by Django 3.0.5 on 2020-05-14 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cumpleanos',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
